name: Test Package

on:
    pull_request:
        branches:
            - "main"

jobs:
    build:
        strategy:
            matrix:
                node-version: [16, 18, 20]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                  version: 7

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: pnpm i --frozen-lockfile

            - name: Check Typescript types
              run: pnpm type-check

            - name: Test
              run: pnpm test
